name: RSpec

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:9.1.0-oraclelinux9
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h 127.0.0.1" --health-interval 5s --health-timeout 5s --health-retries 20
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Set up DB
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate
        env:
          RAILS_ENV: test
      - name: Run RSpec
        run: bundle exec rspec
